import 'package:flutter/material.dart';
import 'package:fl_chart/fl_chart.dart';
import '../../services/duty_service.dart';
import '../../main.dart';

class ReportsScreen extends StatefulWidget {
  const ReportsScreen({super.key});

  @override
  State<ReportsScreen> createState() => _ReportsScreenState();
}

class _ReportsScreenState extends State<ReportsScreen> {
  final _service = DutyService();
  List<Map<String, dynamic>> _performance = [];
  bool _isLoading = true;
  String? _error;
  String _filter = 'All';
  String _period = 'this_school_year';
  int? _touchedIndex;

  static const _filters = ['All', 'Highly Active', 'Moderately Active', 'Low Participation', 'No Data Yet'];
  static const _periods = [
    ('this_school_year', 'School Year'),
    ('this_week',        'This Week'),
    ('this_month',       'This Month'),
    ('last_month',       'Last Month'),
  ];

  @override
  void initState() {
    super.initState();
    _load();
  }

  Future<void> _load() async {
    setState(() { _isLoading = true; _error = null; });
    try {
      final data = await _service.getAllPerformance(period: _period);
      if (mounted) setState(() { _performance = data; _isLoading = false; });
    } catch (_) {
      if (mounted) setState(() { _error = 'Could not connect to server.\nCheck your connection and try again.'; _isLoading = false; });
    }
  }

  int _duties(Map<String, dynamic> m) =>
      int.tryParse(m['total_duties'].toString()) ?? 0;

  int get _totalMembers => _performance.length;
  int get _totalDuties => _performance.fold(0, (s, m) => s + _duties(m));
  int get _participated => _performance.where((m) => _duties(m) > 0).length;
  int get _notParticipated => _performance.where((m) => _duties(m) == 0).length;

  int _countOf(String cls) =>
      _performance.where((m) => m['classification'] == cls).length;

  List<Map<String, dynamic>> get _filtered => _filter == 'All'
      ? _performance
      : _performance.where((m) => m['classification'] == _filter).toList();

  Color _classColor(String? c) {
    switch (c) {
      case 'Highly Active':
        return HudyatColors.success;
      case 'Moderately Active':
        return HudyatColors.warning;
      case 'Low Participation':
        return HudyatColors.accent;
      default:
        return HudyatColors.textSecondary;
    }
  }

  void _showMemberReport(Map<String, dynamic> member) {
    showModalBottomSheet(
      context: context,
      isScrollControlled: true,
      backgroundColor: Colors.transparent,
      builder: (_) => _MemberReportSheet(member: member, service: _service),
    );
  }

  void _showShareDialog() {
    final ha = _countOf('Highly Active');
    final ma = _countOf('Moderately Active');
    final lp = _countOf('Low Participation');
    final avg = _totalMembers == 0 ? 0.0 : _totalDuties / _totalMembers;
    final now = DateTime.now();
    final month = [
      'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun',
      'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'
    ][now.month - 1];

    final report = '''
HUDYAT ORGANIZATION
Performance Report — $month ${now.year}
─────────────────────────────
Total Members   : $_totalMembers
Total Duties    : $_totalDuties
Avg per Member  : ${avg.toStringAsFixed(1)}
─────────────────────────────
Highly Active       : $ha member${ha != 1 ? 's' : ''}
Moderately Active   : $ma member${ma != 1 ? 's' : ''}
Low Participation   : $lp member${lp != 1 ? 's' : ''}
─────────────────────────────
TOP PERFORMERS
${_performance.take(5).map((m) => '  ${(m['full_name'] as String? ?? 'Unknown').padRight(20)} ${_duties(m)} duties').join('\n')}
─────────────────────────────
Generated by HUDYAT Tracker
''';

    showDialog(
      context: context,
      builder: (_) => AlertDialog(
        backgroundColor: HudyatColors.card,
        shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(20)),
        title: const Text(
          'Performance Report',
          style: TextStyle(color: HudyatColors.textPrimary, fontWeight: FontWeight.w700),
        ),
        content: SingleChildScrollView(
          child: Text(
            report,
            style: const TextStyle(
              color: HudyatColors.textSecondary,
              fontSize: 12,
              fontFamily: 'monospace',
              height: 1.6,
            ),
          ),
        ),
        actions: [
          TextButton(
            onPressed: () => Navigator.pop(context),
            child: const Text('Close', style: TextStyle(color: HudyatColors.textSecondary)),
          ),
        ],
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: SafeArea(
        child: _isLoading
            ? const Center(child: CircularProgressIndicator(color: HudyatColors.accent))
            : _error != null
                ? Center(
                    child: Padding(
                      padding: const EdgeInsets.all(32),
                      child: Column(
                        mainAxisAlignment: MainAxisAlignment.center,
                        children: [
                          const Icon(Icons.wifi_off_rounded, size: 52, color: HudyatColors.textSecondary),
                          const SizedBox(height: 16),
                          Text(_error!, textAlign: TextAlign.center, style: const TextStyle(color: HudyatColors.textSecondary, fontSize: 14, height: 1.5)),
                          const SizedBox(height: 24),
                          ElevatedButton.icon(
                            onPressed: _load,
                            icon: const Icon(Icons.refresh_rounded, size: 18),
                            label: const Text('Retry'),
                          ),
                        ],
                      ),
                    ),
                  )
            : RefreshIndicator(
                color: HudyatColors.accent,
                backgroundColor: HudyatColors.card,
                onRefresh: _load,
                child: CustomScrollView(
                  slivers: [
                    // ── Header ─────────────────────────────────────────────
                    SliverToBoxAdapter(
                      child: Padding(
                        padding: const EdgeInsets.fromLTRB(20, 20, 20, 0),
                        child: Row(
                          children: [
                            GestureDetector(
                              onTap: () => Navigator.pop(context),
                              child: Container(
                                padding: const EdgeInsets.all(8),
                                decoration: BoxDecoration(
                                  color: HudyatColors.card,
                                  borderRadius: BorderRadius.circular(12),
                                  border: Border.all(color: HudyatColors.divider),
                                ),
                                child: const Icon(Icons.arrow_back_ios_rounded,
                                    color: HudyatColors.textSecondary, size: 16),
                              ),
                            ),
                            const SizedBox(width: 14),
                            const Expanded(
                              child: Text(
                                'Performance Report',
                                style: TextStyle(
                                  fontSize: 24,
                                  fontWeight: FontWeight.w800,
                                  color: HudyatColors.textPrimary,
                                  letterSpacing: -0.5,
                                ),
                              ),
                            ),
                            GestureDetector(
                              onTap: _showShareDialog,
                              child: Container(
                                padding: const EdgeInsets.all(10),
                                decoration: BoxDecoration(
                                  color: HudyatColors.gold.withOpacity(0.15),
                                  borderRadius: BorderRadius.circular(12),
                                  border: Border.all(color: HudyatColors.gold.withOpacity(0.3)),
                                ),
                                child: const Icon(Icons.summarize_rounded,
                                    color: HudyatColors.gold, size: 20),
                              ),
                            ),
                          ],
                        ),
                      ),
                    ),

                    // ── Period selector ────────────────────────────────────
                    SliverToBoxAdapter(
                      child: Padding(
                        padding: const EdgeInsets.fromLTRB(20, 16, 20, 0),
                        child: Container(
                          padding: const EdgeInsets.all(4),
                          decoration: BoxDecoration(
                            color: HudyatColors.card,
                            borderRadius: BorderRadius.circular(14),
                            border: Border.all(color: HudyatColors.divider),
                          ),
                          child: SingleChildScrollView(
                            scrollDirection: Axis.horizontal,
                            child: Row(
                              children: _periods.map((p) {
                                final selected = _period == p.$1;
                                return GestureDetector(
                                  onTap: () {
                                    if (_period == p.$1) return;
                                    setState(() { _period = p.$1; _touchedIndex = null; });
                                    _load();
                                  },
                                  child: AnimatedContainer(
                                    duration: const Duration(milliseconds: 200),
                                    padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 10),
                                    decoration: BoxDecoration(
                                      color: selected ? HudyatColors.accent : Colors.transparent,
                                      borderRadius: BorderRadius.circular(10),
                                    ),
                                    alignment: Alignment.center,
                                    child: Text(
                                      p.$2,
                                      style: TextStyle(
                                        color: selected ? Colors.white : HudyatColors.textSecondary,
                                        fontSize: 11,
                                        fontWeight: selected ? FontWeight.w700 : FontWeight.w500,
                                      ),
                                    ),
                                  ),
                                );
                              }).toList(),
                            ),
                          ),
                        ),
                      ),
                    ),

                    // ── Summary stats ──────────────────────────────────────
                    SliverToBoxAdapter(
                      child: Padding(
                        padding: const EdgeInsets.fromLTRB(20, 16, 20, 0),
                        child: Row(
                          children: [
                            _MiniStat(label: 'Members', value: '$_totalMembers', color: Colors.blueAccent),
                            const SizedBox(width: 10),
                            _MiniStat(label: 'Duties', value: '$_totalDuties', color: HudyatColors.accent),
                            const SizedBox(width: 10),
                            _MiniStat(
                              label: 'Avg Duties',
                              value: (_totalMembers == 0 ? 0.0 : _totalDuties / _totalMembers)
                                  .toStringAsFixed(1),
                              color: HudyatColors.gold,
                            ),
                          ],
                        ),
                      ),
                    ),

                    // ── Donut chart ────────────────────────────────────────
                    SliverToBoxAdapter(
                      child: Padding(
                        padding: const EdgeInsets.fromLTRB(20, 20, 20, 0),
                        child: Container(
                          padding: const EdgeInsets.all(20),
                          decoration: BoxDecoration(
                            color: HudyatColors.card,
                            borderRadius: BorderRadius.circular(20),
                            border: Border.all(color: HudyatColors.divider),
                          ),
                          child: Column(
                            children: [
                              const Text(
                                'Participation Overview',
                                style: TextStyle(
                                  color: HudyatColors.textPrimary,
                                  fontWeight: FontWeight.w700,
                                  fontSize: 14,
                                ),
                              ),
                              const SizedBox(height: 20),
                              if (_totalDuties == 0 && _period != 'this_school_year')
                                const Padding(
                                  padding: EdgeInsets.symmetric(vertical: 28),
                                  child: Column(
                                    children: [
                                      Icon(Icons.event_busy_rounded, size: 40, color: HudyatColors.textSecondary),
                                      SizedBox(height: 12),
                                      Text(
                                        'No events this period',
                                        style: TextStyle(color: HudyatColors.textSecondary, fontSize: 13, fontWeight: FontWeight.w600),
                                      ),
                                    ],
                                  ),
                                )
                              else
                                SizedBox(
                                  height: 180,
                                  child: Row(
                                    children: [
                                      Expanded(
                                        child: PieChart(
                                          PieChartData(
                                            pieTouchData: PieTouchData(
                                              touchCallback: (event, response) {
                                                setState(() {
                                                  if (!event.isInterestedForInteractions ||
                                                      response == null ||
                                                      response.touchedSection == null) {
                                                    _touchedIndex = null;
                                                    return;
                                                  }
                                                  _touchedIndex = response
                                                      .touchedSection!.touchedSectionIndex;
                                                });
                                              },
                                            ),
                                            centerSpaceRadius: 50,
                                            sectionsSpace: 3,
                                            sections: _buildPieSections(),
                                          ),
                                        ),
                                      ),
                                      const SizedBox(width: 16),
                                      Column(
                                        mainAxisAlignment: MainAxisAlignment.center,
                                        crossAxisAlignment: CrossAxisAlignment.start,
                                        children: [
                                          _PieLegend(color: HudyatColors.success, label: 'Participated', count: _participated, total: _totalMembers),
                                          const SizedBox(height: 10),
                                          _PieLegend(color: HudyatColors.accent, label: 'Not Participated', count: _notParticipated, total: _totalMembers),
                                        ],
                                      ),
                                    ],
                                  ),
                                ),
                            ],
                          ),
                        ),
                      ),
                    ),

                    // ── Filter chips ───────────────────────────────────────
                    SliverToBoxAdapter(
                      child: Padding(
                        padding: const EdgeInsets.fromLTRB(20, 20, 20, 0),
                        child: SingleChildScrollView(
                          scrollDirection: Axis.horizontal,
                          child: Row(
                            children: _filters.map((f) {
                              final selected = _filter == f;
                              final color = f == 'Highly Active'
                                  ? HudyatColors.success
                                  : f == 'Moderately Active'
                                      ? HudyatColors.warning
                                      : f == 'Low Participation'
                                          ? HudyatColors.accent
                                          : HudyatColors.textSecondary;
                              return Padding(
                                padding: const EdgeInsets.only(right: 8),
                                child: GestureDetector(
                                  onTap: () => setState(() => _filter = f),
                                  child: AnimatedContainer(
                                    duration: const Duration(milliseconds: 200),
                                    padding: const EdgeInsets.symmetric(horizontal: 14, vertical: 8),
                                    decoration: BoxDecoration(
                                      color: selected ? color.withOpacity(0.2) : HudyatColors.card,
                                      borderRadius: BorderRadius.circular(20),
                                      border: Border.all(
                                        color: selected ? color : HudyatColors.divider,
                                        width: selected ? 1.5 : 1,
                                      ),
                                    ),
                                    child: Text(
                                      f,
                                      style: TextStyle(
                                        color: selected ? color : HudyatColors.textSecondary,
                                        fontSize: 12,
                                        fontWeight: selected ? FontWeight.w700 : FontWeight.w500,
                                      ),
                                    ),
                                  ),
                                ),
                              );
                            }).toList(),
                          ),
                        ),
                      ),
                    ),

                    // ── Member count label ─────────────────────────────────
                    SliverToBoxAdapter(
                      child: Padding(
                        padding: const EdgeInsets.fromLTRB(20, 16, 20, 8),
                        child: Text(
                          '${_filtered.length} member${_filtered.length != 1 ? 's' : ''}',
                          style: const TextStyle(
                            color: HudyatColors.textSecondary,
                            fontSize: 12,
                            fontWeight: FontWeight.w600,
                          ),
                        ),
                      ),
                    ),

                    // ── Member list ────────────────────────────────────────
                    SliverPadding(
                      padding: const EdgeInsets.fromLTRB(20, 0, 20, 32),
                      sliver: SliverList(
                        delegate: SliverChildBuilderDelegate(
                          (context, index) {
                            final m = _filtered[index];
                            final cls = m['classification'] as String?;
                            final color = _classColor(cls);
                            final name = m['full_name'] as String? ?? 'Unknown';
                            final initials = name
                                .split(' ')
                                .map((e) => e.isNotEmpty ? e[0] : '')
                                .take(2)
                                .join()
                                .toUpperCase();
                            return Padding(
                              padding: const EdgeInsets.only(bottom: 10),
                              child: GestureDetector(
                                onTap: () => _showMemberReport(m),
                                child: Container(
                                  padding: const EdgeInsets.all(16),
                                  decoration: BoxDecoration(
                                    color: HudyatColors.card,
                                    borderRadius: BorderRadius.circular(16),
                                    border: Border.all(color: HudyatColors.divider),
                                  ),
                                  child: Row(
                                    children: [
                                      Container(
                                        width: 44,
                                        height: 44,
                                        decoration: BoxDecoration(
                                          color: color.withOpacity(0.15),
                                          borderRadius: BorderRadius.circular(12),
                                        ),
                                        alignment: Alignment.center,
                                        child: Text(
                                          initials,
                                          style: TextStyle(
                                            color: color,
                                            fontWeight: FontWeight.w700,
                                            fontSize: 14,
                                          ),
                                        ),
                                      ),
                                      const SizedBox(width: 12),
                                      Expanded(
                                        child: Column(
                                          crossAxisAlignment: CrossAxisAlignment.start,
                                          children: [
                                            Text(
                                              name,
                                              style: const TextStyle(
                                                color: HudyatColors.textPrimary,
                                                fontWeight: FontWeight.w600,
                                                fontSize: 14,
                                              ),
                                            ),
                                            const SizedBox(height: 3),
                                            _InlineTag(
                                              label: '${_duties(m)} duties',
                                              color: color,
                                            ),
                                          ],
                                        ),
                                      ),
                                      const Icon(Icons.chevron_right_rounded,
                                          color: HudyatColors.textSecondary, size: 16),
                                    ],
                                  ),
                                ),
                              ),
                            );
                          },
                          childCount: _filtered.length,
                        ),
                      ),
                    ),
                  ],
                ),
              ),
      ),
    );
  }

  List<PieChartSectionData> _buildPieSections() {
    final data = [
      (_participated, HudyatColors.success, 0),
      (_notParticipated, HudyatColors.accent, 1),
    ];

    return data.map((entry) {
      final count = entry.$1;
      final color = entry.$2;
      final index = entry.$3;
      final isTouched = index == _touchedIndex;
      final pct = _totalMembers == 0 ? 0.0 : (count / _totalMembers) * 100;

      return PieChartSectionData(
        value: count.toDouble(),
        color: color,
        radius: isTouched ? 46 : 38,
        title: pct >= 10 ? '${pct.toStringAsFixed(0)}%' : '',
        titleStyle: const TextStyle(
          fontSize: 11,
          fontWeight: FontWeight.w800,
          color: Colors.white,
        ),
        badgeWidget: isTouched
            ? Container(
                padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 4),
                decoration: BoxDecoration(
                  color: color,
                  borderRadius: BorderRadius.circular(8),
                ),
                child: Text(
                  '$count',
                  style: const TextStyle(
                    color: Colors.white,
                    fontWeight: FontWeight.w800,
                    fontSize: 12,
                  ),
                ),
              )
            : null,
        badgePositionPercentageOffset: 1.3,
      );
    }).toList();
  }
}

// ── Individual Member Report Sheet ─────────────────────────────────────────────

class _MemberReportSheet extends StatefulWidget {
  final Map<String, dynamic> member;
  final DutyService service;

  const _MemberReportSheet({required this.member, required this.service});

  @override
  State<_MemberReportSheet> createState() => _MemberReportSheetState();
}

class _MemberReportSheetState extends State<_MemberReportSheet> {
  List<Map<String, dynamic>> _duties = [];
  bool _loading = true;

  @override
  void initState() {
    super.initState();
    _load();
  }

  Future<void> _load() async {
    try {
      final duties = await widget.service.getDutiesByMember(
        widget.member['id'].toString(),
      );
      if (mounted) setState(() { _duties = duties; _loading = false; });
    } catch (_) {
      if (mounted) setState(() => _loading = false);
    }
  }

  Color _classColor(String? c) {
    switch (c) {
      case 'Highly Active': return HudyatColors.success;
      case 'Moderately Active': return HudyatColors.warning;
      case 'Low Participation': return HudyatColors.accent;
      default: return HudyatColors.textSecondary;
    }
  }

  String _formatDate(String? raw) {
    if (raw == null) return '';
    try {
      final d = DateTime.parse(raw);
      const months = ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];
      return '${months[d.month - 1]} ${d.day}, ${d.year}';
    } catch (_) { return raw; }
  }

  @override
  Widget build(BuildContext context) {
    final m = widget.member;
    final name = m['full_name'] as String? ?? 'Unknown';
    final cls = m['classification'] as String?;
    final clsColor = _classColor(cls);
    final initials = name.split(' ').map((e) => e.isNotEmpty ? e[0] : '').take(2).join().toUpperCase();
    final totalDuties = int.tryParse(m['total_duties'].toString()) ?? 0;

    return Container(
      decoration: const BoxDecoration(
        color: HudyatColors.card,
        borderRadius: BorderRadius.vertical(top: Radius.circular(28)),
      ),
      padding: const EdgeInsets.fromLTRB(24, 12, 24, 40),
      constraints: BoxConstraints(
        maxHeight: MediaQuery.of(context).size.height * 0.85,
      ),
      child: Column(
        mainAxisSize: MainAxisSize.min,
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          // Drag handle
          Center(
            child: Container(
              width: 40, height: 4,
              decoration: BoxDecoration(color: HudyatColors.divider, borderRadius: BorderRadius.circular(2)),
            ),
          ),
          const SizedBox(height: 20),

          // Header
          Row(
            children: [
              Container(
                width: 52, height: 52,
                decoration: BoxDecoration(
                  color: clsColor.withOpacity(0.15),
                  borderRadius: BorderRadius.circular(16),
                ),
                alignment: Alignment.center,
                child: Text(initials, style: TextStyle(color: clsColor, fontWeight: FontWeight.w800, fontSize: 18)),
              ),
              const SizedBox(width: 14),
              Expanded(
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Text(name, style: const TextStyle(color: HudyatColors.textPrimary, fontWeight: FontWeight.w800, fontSize: 18)),
                    const SizedBox(height: 4),
                    Container(
                      padding: const EdgeInsets.symmetric(horizontal: 10, vertical: 3),
                      decoration: BoxDecoration(
                        color: clsColor.withOpacity(0.12),
                        borderRadius: BorderRadius.circular(20),
                        border: Border.all(color: clsColor.withOpacity(0.35)),
                      ),
                      child: Text(
                        cls ?? 'No Data Yet',
                        style: TextStyle(color: clsColor, fontSize: 11, fontWeight: FontWeight.w700),
                      ),
                    ),
                  ],
                ),
              ),
            ],
          ),
          const SizedBox(height: 16),

          // Stats
          Row(
            children: [
              _ReportStat(label: 'Total Duties', value: '$totalDuties', color: clsColor),
              const SizedBox(width: 10),
              _ReportStat(label: 'Event Coverage', value: '${m['events_attended'] ?? 0}/${m['total_events'] ?? 0}', color: HudyatColors.gold),
              const SizedBox(width: 10),
              _ReportStat(label: 'Student ID', value: m['student_id'] ?? '—', color: HudyatColors.textSecondary),
            ],
          ),
          const SizedBox(height: 20),

          // Duty history label
          const Text(
            'DUTY HISTORY',
            style: TextStyle(color: HudyatColors.textSecondary, fontSize: 11, fontWeight: FontWeight.w700, letterSpacing: 1),
          ),
          const SizedBox(height: 10),

          // Duty list
          Flexible(
            child: _loading
                ? const Center(child: Padding(
                    padding: EdgeInsets.all(24),
                    child: CircularProgressIndicator(color: HudyatColors.accent, strokeWidth: 2),
                  ))
                : _duties.isEmpty
                    ? const Center(
                        child: Padding(
                          padding: EdgeInsets.all(24),
                          child: Text('No duties recorded yet.', style: TextStyle(color: HudyatColors.textSecondary, fontStyle: FontStyle.italic)),
                        ),
                      )
                    : ListView.separated(
                        shrinkWrap: true,
                        itemCount: _duties.length,
                        separatorBuilder: (_, __) => const SizedBox(height: 8),
                        itemBuilder: (context, i) {
                          final d = _duties[i];
                          final notes = d['notes'] as String? ?? '';
                          return Container(
                            padding: const EdgeInsets.all(14),
                            decoration: BoxDecoration(
                              color: HudyatColors.cardElevated,
                              borderRadius: BorderRadius.circular(14),
                            ),
                            child: Column(
                              crossAxisAlignment: CrossAxisAlignment.start,
                              children: [
                                Row(
                                  children: [
                                    Expanded(
                                      child: Text(
                                        d['event_name'] ?? 'Unknown Event',
                                        style: const TextStyle(color: HudyatColors.textPrimary, fontWeight: FontWeight.w600, fontSize: 13),
                                      ),
                                    ),
                                    Text(
                                      _formatDate(d['event_date']),
                                      style: const TextStyle(color: HudyatColors.textSecondary, fontSize: 11),
                                    ),
                                  ],
                                ),
                                const SizedBox(height: 6),
                                Row(
                                  children: [
                                    Container(
                                      padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 2),
                                      decoration: BoxDecoration(
                                        color: HudyatColors.accent.withOpacity(0.12),
                                        borderRadius: BorderRadius.circular(6),
                                      ),
                                      child: Text(
                                        d['role_assigned'] ?? '',
                                        style: const TextStyle(color: HudyatColors.accent, fontSize: 11, fontWeight: FontWeight.w600),
                                      ),
                                    ),
                                  ],
                                ),
                                if (notes.isNotEmpty) ...[
                                  const SizedBox(height: 6),
                                  Text(
                                    notes,
                                    style: const TextStyle(color: HudyatColors.textSecondary, fontSize: 12, fontStyle: FontStyle.italic),
                                  ),
                                ],
                              ],
                            ),
                          );
                        },
                      ),
          ),
        ],
      ),
    );
  }
}

class _ReportStat extends StatelessWidget {
  final String label;
  final String value;
  final Color color;

  const _ReportStat({required this.label, required this.value, required this.color});

  @override
  Widget build(BuildContext context) {
    return Expanded(
      child: Container(
        padding: const EdgeInsets.all(12),
        decoration: BoxDecoration(
          color: HudyatColors.cardElevated,
          borderRadius: BorderRadius.circular(12),
        ),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Text(value, style: TextStyle(color: color, fontSize: 16, fontWeight: FontWeight.w800)),
            const SizedBox(height: 2),
            Text(label, style: const TextStyle(color: HudyatColors.textSecondary, fontSize: 10)),
          ],
        ),
      ),
    );
  }
}

class _MiniStat extends StatelessWidget {
  final String label;
  final String value;
  final Color color;

  const _MiniStat({required this.label, required this.value, required this.color});

  @override
  Widget build(BuildContext context) {
    return Expanded(
      child: Container(
        padding: const EdgeInsets.all(14),
        decoration: BoxDecoration(
          color: HudyatColors.card,
          borderRadius: BorderRadius.circular(14),
          border: Border.all(color: HudyatColors.divider),
        ),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Text(value, style: TextStyle(color: color, fontSize: 20, fontWeight: FontWeight.w800)),
            const SizedBox(height: 2),
            Text(label, style: const TextStyle(color: HudyatColors.textSecondary, fontSize: 11)),
          ],
        ),
      ),
    );
  }
}

class _PieLegend extends StatelessWidget {
  final Color color;
  final String label;
  final int count;
  final int total;

  const _PieLegend({required this.color, required this.label, required this.count, required this.total});

  @override
  Widget build(BuildContext context) {
    final pct = total == 0 ? 0.0 : (count / total) * 100;
    return Row(
      children: [
        Container(width: 10, height: 10, decoration: BoxDecoration(color: color, shape: BoxShape.circle)),
        const SizedBox(width: 8),
        Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Text(label, style: const TextStyle(color: HudyatColors.textPrimary, fontSize: 12, fontWeight: FontWeight.w600)),
            Text('$count  (${pct.toStringAsFixed(0)}%)',
                style: const TextStyle(color: HudyatColors.textSecondary, fontSize: 11)),
          ],
        ),
      ],
    );
  }
}

class _InlineTag extends StatelessWidget {
  final String label;
  final Color color;

  const _InlineTag({required this.label, required this.color});

  @override
  Widget build(BuildContext context) {
    return Container(
      padding: const EdgeInsets.symmetric(horizontal: 7, vertical: 2),
      decoration: BoxDecoration(
        color: color.withValues(alpha: 0.12),
        borderRadius: BorderRadius.circular(6),
      ),
      child: Text(
        label,
        style: TextStyle(color: color, fontSize: 11, fontWeight: FontWeight.w600),
      ),
    );
  }
}
